//search
    QID_ITEMPRICE_LOAD,

//add after
#ifdef ENABLE_IKASHOP_RENEWAL
	QID_OFFLINESHOP_ADD_ITEM,
	QID_OFFLINESHOP_EDIT_ITEM,
	QID_OFFLINESHOP_DELETE_SHOP,
	QID_OFFLINESHOP_DELETE_SHOP_ITEM,
	QID_OFFLINESHOP_REMOVE_ITEM,
	QID_OFFLINESHOP_UPDATE_SOLD_ITEM,

	QID_OFFLINESHOP_CREATE_SHOP,
	QID_OFFLINESHOP_SHOP_CHANGE_NAME,
	QID_OFFLINESHOP_SHOP_UPDATE_DURATION,

	QID_OFFLINESHOP_SAFEBOX_DELETE_ITEM,
	QID_OFFLINESHOP_SAFEBOX_ADD_ITEM,
	QID_OFFLINESHOP_SAFEBOX_UPDATE_VALUTES,
	QID_OFFLINESHOP_SAFEBOX_INSERT_VALUTES,
	QID_OFFLINESHOP_SAFEBOX_UPDATE_VALUTES_ADDING,
#endif